import datetime
data=datetime.datetime.utcnow()
print(data.year)
print(data.month)
print(data.day)
print(data.strftime("%a"))
print(data.strftime("%A"))
print(data.strftime("%w"))
print(data.strftime("%d"))
#print(data.strftime("%-d"))
print(data.strftime("%b"))
print(data.strftime("%B"))
print(data.strftime("%m"))
#print(data.strftime("%-m"))
print(data.strftime("%y"))
#print(data.strftime("%-y"))
print(data.strftime("%Y"))
print(data.strftime("%H"))
#print(data.strftime("%-H"))
print(data.strftime("%I"))
#print(data.strftime("%-I"))
print(data.strftime("%p"))
print(data.strftime("%M"))
#print(data.strftime("%-M"))
print(data.strftime("%S"))
#print(data.strftime("%-S"))
print(data.strftime("%f"))
print(data.strftime("%z"))
print(data.strftime("%Z"))
print(data.strftime("%j"))
#print(data.strftime("%-j"))
print(data.strftime("%U"))
print(data.strftime("%W"))
print(data.strftime("%c"))
print(data.strftime("%x"))
print(data.strftime("%X"))
print(data.strftime("%%"))




